max_width = 100
tab_spaces = 2
struct_field_align_threshold = 40
enum_discrim_align_threshold = 40
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
match_arm_blocks = false
overflow_delimited_expr = true
chain_width = 90
fn_call_width = 90

